src/commons/string.h
Evita confusiones con la `append`ación de strings.
=> Doc de String_append

README.md
@francopesce: ¿Te parece bien así?
Fixes #52
=> Explicación para linkear en eclipse

src/commons/collections/list.c
Para que no le envíe NULL a element_destroyer
=> cambio en list_remove_and_destroy_by_condition

src/commons/string.c, src/commons/string.h, tests/unit-tests/test_string.c
=> add string_reverse(..)

src/commons/config.c, tests/unit-tests/resources/config.cfg, tests/unit-tests/test_config.c
=> config_get_string_value supports values with = sign

src/commons/config.h
Agrego que el array que devuelve termina en NULL
=> Agrego documentacion a 'config_get_array_value'

tests/unit-tests/test_list.c
=> Spec mostrando parametros para la funcion de list_find

src/commons/bitarray.c, src/commons/bitarray.h, tests/unit-tests/test_bitarray.c
Implementing BitArray Bit Endianness MSB/LSB selecting on create time.
=> Bitarray Bit Numbering implementation

src/commons/string.c, src/commons/string.h, tests/unit-tests/test_string.c
CC: @jaecisneros @gastonprieto
Fixes #66
=> string_contains wraps strstr standard function

src/commons/temporal.c
https://github.com/sisoputnfrba/so-commons-library/issues/87
=> Usar funcion thread-safe para calcular fechas

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
=> Agrego una funcion para duplicar el contenido de una lista #99

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Agrego list_sorted para resolver #99
=> Feature list sorted

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Adding new lists function called 'list_fold' which lets you fold a list into a single value, with a given function.
That function should accept 2 values of the data type found in the list, and return a value of the same data type.
=> Feature list_fold

src/commons/memory.c, src/commons/memory.h, tests/unit-tests/test_memory.c
=> Agrego #mem_hexstring y #mem_hexdump

src/commons/bitarray.h
Estuve viendo mucha confusión al respecto en el foro este cuatrimestre, así pensé en aclarar un poco la descripción sobre la firma de esta función, a ver si ayuda un poco en el futuro
=> aclaro descrpcion de bitarray_create

src/commons/collections/list.c, tests/unit-tests/test_list.c
La idea de este commit es unificar el funcionamiento de (casi) todas las funciones de listas en base a las operaciones más básicas:
-. list_link_element
-. list_unlink_element
-. list_create_element
-. list_get_last_element
-. list_find_element
-. list_add_element
-. list_remove_element
-. list_append_to_sublist
Esto me sirvió mucho para simplificar el desarrollo de nuevas funciones que voy a subir en otros Pull Request.
=> Refactor funciones de listas

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Para desarrollar esta feature, me basé en el refactor en https://github.com/sisoputnfrba/so-commons-library/pull/126
Agrego una nueva estructura `t_list_iterator` que soporta las 3 operaciones básicas mencionadas acá https://github.com/sisoputnfrba/so-commons-library/issues/80 y funciona como se propone acá https://github.com/sisoputnfrba/so-commons-library/pull/78 :
```C
t_list* myList = createExampleList(); 
t_list_iterator* iterator = list_iterator_start(myList);
while (list_iterator_has_next(iterator)) {
t_myData* element = list_iterator_next(iterator);
if (myConditionToRemove(element)) {
list_iterator_remove(iterator);
}
}
list_iterator_end(iterator);
```
No incluí un `add()` porque no sabría bien si la idea sería agregar el elemento nuevo en la posición de `iterator->index`, o si …
=> Listas: Un iterador externo

CHANGELOG.md, src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Agrego las funciones `fold1()`, `get_minimum()` y `get_maximum()` sugeridas acá: https://github.com/sisoputnfrba/so-commons-library/issues/116
Al tratarse de foldeos, hice que tanto minimum como maximum usen un comparador entre dos elementos que devuelva la diferencia entre el primero y el segundo para así poder decidir cuál es el menor o el mayor entre ambos. Esto pensando en el comportamiento de la función `strcmp(2)`.
```C
/**
* @NAME: list_get_minimum
* @DESC: Retorna el minimo de la lista según el comparador
* El comparador devuelve la diferencia entre el valor del primer 
* parámetro y el del segundo
*/
void *list_get_minimum(t_list* self, int (*comparator)(void*, void*));
/**
* @NAME: list_get_maximum
* @DESC: Retorna el maximo de la lista según el comparador
* El comparador …
```
=> Listas: Nuevos foldeos

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Agrego la función `list_slice_and_remove`, emulando a [Array splice en JS](https://www.w3schools.com/jsref/jsref_splice.asp)
```c
/**
* @NAME: list_slice_and_remove
* @DESC: Retorna una nueva lista con los primeros n elementos partiendo 
* desde el índice indicado, eliminando del origen estos elementos.
*/
t_list* list_slice_and_remove(t_list* self, int start, int count);
```
Y la función `list_slice`, que haría lo mismo pero sin remover esos elementos:
```c
/**
* @NAME: list_slice
* @DESC: Retorna una nueva lista con los primeros n elementos partiendo 
* desde el índice indicado.
*/
t_list* list_slice(t_list* self, int start, int count);
```
Creo que sería útil soportarlas ya que son una versión más genérica de `list_take` y `list_take_and_remove`.
=> Listas: Slice

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Al parecer, revisando las branches en mi fork me di cuenta de que me olvidé de armar el PR de `list_remove_and_destroy_all_by_condition` que había hecho en #124. 🤦🏻‍♂️ 
```c
/**
* @NAME: list_remove_and_destroy_all_by_condition
* @DESC: Remueve y destruye todos los elementos de
* la lista que hagan que condition devuelva != 0.
*/
void list_remove_and_destroy_all_by_condition(t_list *self, bool(*condition)(void*), void(*element_destroyer)(void*));
``` 
Resuelve #105
=> Listas: Remove and destroy all by condition

src/commons/string.c, tests/unit-tests/test_string.c
Me di cuenta que en #133 introduje operaciones que ocultan errores (incluso se testea que esos errores se oculten). Creería que no es un comportamiento deseado, por lo que este PR sería para corregirlo.
=> Strings: string array fixes

src/commons/collections/list.c, src/commons/collections/list.h, src/commons/collections/queue.c, src/commons/collections/queue.h
Actualizo el tipado del retorno de `queue_is_empty` y  `list_is_empty`.
=> Update list_is_empty and queue_is_empty

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Me vi [la charla TED de Linus Torvalds](https://youtu.be/o8NPllzkFhE?t=858) y en una parte mostraba que era posible quitar un elemento de una linked list sin ese `if` que chequea que sea el head de la lista:
Entonces me dije "¿por qué no implementarlo para las commons?" 😅 
Una cosa llevó a la otra y ahora resulta que me quedó **oootro** refactor de listas (esta vez sin tantas nested functions). Btw creo que el código incluso quedó más fácil de leer por si se lo tuviera que explicar a alguien.
=> Yet Another List Refactor

src/commons/temporal.c, src/commons/temporal.h, tests/integration-tests/temporal/main.c
Funciones para manejar temporales en milisegundos y tests de integración al respecto.
- Crear un temporal.
- Destruir un temporal.
- Obtener el tiempo total transcurrido.
- Obtener el tiempo transcurrido en el último período activo del temporal.
- Detener.
- Reanudar.
- Comparar dos variables temporales.
=> feat: api para manejo de timestamps (#156)

Dockerfile
=> sh to bash and add valgrind

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
Caso de uso: tengo una lista de tablas de páginas (`t_list*` de `t_list*` de `t_página*`) y quiero aplicar el algoritmo de reemplazo involucrando todas las páginas presentes.
=> feat: List Flatten

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
```c
/**
* @NAME: list_iterator_index
* @DESC: Devuelve el índice del elemento actual de la iteración
*/
int list_iterator_index(t_list_iterator* iterator);
/**
* @NAME: list_iterator_add
* @DESC: Agrega a la lista un elemento delante del actual y detrás
* del siguiente. Luego, avanza hacia el elemento agregado.
*/
void list_iterator_add(t_list_iterator* iterator, void *data);
```
=> List: Iterator Index y Add

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
```c
/**
* @NAME: list_replace_by_condition
* @DESC: Coloca un elemento en la posición de la lista
* en donde se encuentra el primer valor que haga que
* condition sea != 0, retornando el valor anterior.
*
* En caso de no encontrar ningún valor, no realiza el
* reemplazo y retorna NULL.
*/
void *list_replace_by_condition(t_list*, bool(*condition)(void*), void* element);
```
closes #34
=> list: replace by condition

src/commons/collections/list.c, src/commons/collections/list.h, tests/unit-tests/test_list.c
```c
/**
* @NAME: list_remove_element
* @DESC: Remueve al elemento de la lista recibido por parámetro. Devuelve
* false en caso de no haberlo encontrado.
*/
bool list_remove_element(t_list* self, void* element);
```
closes #34
=> list: remove element

.gitignore, src/commons/bitarray.h, src/commons/collections/dictionary.c, src/commons/collections/dictionary.h, src/commons/collections/list.h, src/commons/collections/queue.h, src/commons/config.h, src/commons/error.h, src/commons/log.h, src/commons/memory.h, src/commons/process.h, src/commons/string.h, src/commons/temporal.h, src/commons/txt.h, tests/integration-tests/temporal/main.c
resolves #171 
Enums:
Funciones:
=> Docs: convierto a doxygen

src/commons/bitarray.h, src/commons/collections/dictionary.h, src/commons/collections/list.h, src/commons/collections/queue.h, src/commons/config.h, src/commons/log.h, src/commons/memory.h, src/commons/process.h, src/commons/string.h, src/commons/temporal.h
Literalmente todas las descripciones de log.h quedaron mal :S
Moraleja: Nunca usen un regex para esto
=> Docs: Fix doxygen comments
