sisoputnfrba/so-commons-library

- src/commons/config.c
- tests/unit-tests/test_config.c
Si `config_create` no puede abrir el path, devuelve `NULL` para que el usuario pueda saber si la creacion del t_config fue exitosa o no.
Creo que en algún momento lo habíamos discutido con @gastonprieto, no recuerdo si él tenía motivos para _no_ hacerlo, o si simplemente no lo habíamos hecho por fiaca.
Me inspiré por [este thread](http://www.campusvirtual.frba.utn.edu.ar/especialidad/mod/forum/discuss.php?d=34130) en el que hablaban entre @alkchofa y @janopn
> config_create devuelve NULL si no se puede abrir el path

- .travis.yml
- README.md
- tests/unit-tests/makefile
TravisCI se integra con GitHub mostrando el estado del build en cada push - bastante util a la hora de evaluar si mergear o no un PR.
Drone sigue prendido, no creo que me moleste que este ahi, pero tener a Travis opinando esta bueno.
CC: @gastonprieto @mdumrauf
Related: #40
> TravisCI build

- src/commons/collections/list.c
Before calling closure() on list_iterate(), the element->next can be saved in an aux variable, so if the element is removed (using either remove by condition or destroy), the iteration still works.
> Store element->next before closure on list_iterate

- src/commons/log.c
Usefull-ish feature.
*Only* in console output it logs the levels with colors:
- RED for ERROR
- ORANGE/YELLOW for WARNING
- GREEN for DEBUG
- BLUE for TRACE
- Normal for INFO
> added terminal color support for log levels

- src/commons/config.c
Loggeo un warning cuando `config_create` detecta un `\r\n` en el archivo de configuración.
Fixes #83 
CC: @gastonprieto
> Detect and warn about Windows newlines in config files

- src/commons/string.c
- tests/unit-tests/resources/config-double-newline.cfg
- tests/unit-tests/test_config.c
Parece que #56 en realidad venía porque `string_split` pincha cuando el texto termina con el token.
Quizá habría que hacer algún spec más sobre ese caso en particular.
CC: @gastonprieto
> Halt string_split tokenization if there are no more tokens

- src/commons/string.c
- src/commons/string.h
Ya devolvía un bool, pero decía devolver un string.
Fixes #92
Gracias @gerosamore!
> Corregir el prototipo de string_contains

- .travis.yml
- makefile
- tests/unit-tests/makefile
Se cambia para que no pase el build de travis si hay algún memory leak.
(Lo robé de [acá](https://github.com/open-source-parsers/jsoncpp/pull/265))
> added leak checks in CI

- src/commons/log.c
- src/commons/temporal.c
- src/commons/temporal.h
- tests/integration-tests/logger/main.c
- tests/integration-tests/temporal/main.c
- tests/integration-tests/temporal/makefile
Para el cuatri pasado me acuerdo que había que poner en el dump de la caché del Broker la fecha en formato `dd/mm/yy HH:MM:SS`. En su día tuve que hacer una función porque `temporal_get_string_time` solo admite un único formato para mostrar (que se usa solo para los loggers).
Solo funciona enviando los formatos que tienen el mismo tamaño que el token (lo cual me pareció suficiente): 
%d (día) %m (mes) %y (año en 2 dígitos) %H (horas 0-23) %M (minutos) %S (segundos) %MS (milisegundos, este último fue creado para poder mostrarlos de una forma más amigable).
Igualmente, se podría aprovechar la función `string_replace` que subí en otro PR para agregarle un par de formatos extra.
EDIT: Vi que al usar `ftime(3)` tira warning y se recomienda el uso de `clock_gettime(2)` ya que es más portable, …
> Refactor Temporal

- src/commons/config.c
- src/commons/string.c
- src/commons/string.h
- tests/unit-tests/test_config.c
- tests/unit-tests/test_string.c
Este PR incluye:
Fix del bug de `string_split` (https://github.com/sisoputnfrba/so-commons-library/issues/57) , ahora usa `strsep` en vez de `strtok_r`, lo cual permite que se comporte como se esperaba:
```
//Antes: 
string_split("//path//to/file/","/"); => ["path", "to", "file", NULL]
string_split("", "/") => [NULL] 
//Ahora: 
string_split("//path//to/file/","/"); => ["", "", "path", "", "to", "file", "", NULL]
string_split("","/") => ["", NULL]
```
> Strings: Fix string_split

- src/commons/collections/list.c
- src/commons/collections/list.h
- tests/unit-tests/test_list.c
Para desarrollar esta feature, me basé en el refactor en https://github.com/sisoputnfrba/so-commons-library/pull/126
Me pareció útil agregar un `add_sorted()` para las funciones de listas, que funciona utilizando el mismo tipo de comparador que se usa en `sort()` y `sorted()`:
```c
/**
* @NAME: list_add_sorted
* @DESC: Agrega un elemento a una lista ordenada, manteniendo el
* orden definido por el comparador
* El comparador devuelve si el primer parametro debe aparecer antes que el
* segundo en la lista
*/
int list_add_sorted(t_list *self, void* element, bool (*comparator)(void*,void*));
```
> Listas: Insertar ordenado

- .travis.yml
- README.md
- makefile
- src/makefile
- tests/unit-tests/makefile
Al codear para los otros PRs, incluí reglas para evitar rebuilds y para que los unit-tests no hagan "nothing to be done for all" cuando solo fixee algo de los srcs xd
También, de paso, vi que ahora estamos haciendo `make && sudo make install` para instalar cuando en realidad se puede incluir el sudo solo al copiar los archivos a `/usr`, de esa forma se evita tener problemas con los permisos al hacer solo `make install`.
> Makefiles para evitar rebuilds

- src/commons/config.c
- src/commons/string.c
- src/commons/string.h
- tests/unit-tests/test_config.c
- tests/unit-tests/test_string.c
Este PR incluye un par de funciones muy sencillas para manejar arrays de strings:
2.1. string_array_new
2.2. string_array_size (https://github.com/sisoputnfrba/so-commons-library/issues/43) y string_array_is_empty
2.3. string_array_push, pop y replace
2.4. string_array_destroy
Para hacer push, funciona igual que como se hace en el `_string_split` original: hace `realloc` cada vez que se agregue un elemento. Para hacer pop, solamente alcanza con reemplazar la posición en donde estaba por NULL (y se devuelve como en un list_remove).
> Strings: operaciones para string arrays

- src/commons/string.c
- tests/unit-tests/test_string.c
Resuelve #141 
Ahora tiene un comportamiento 100% igual a [split en JS](https://www.w3schools.com/jsref/jsref_split.asp#:~:text=The%20split()%20method%20is,not%20change%20the%20original%20string.):
- El delimitador es un string (en vez de ser todos los caracteres que lo componen)
- Si el delimitador es string vacío, hace un array de strings con cada caracter
- Si el delimitador es nulo, devuelve un array cuyo primer valor es el string completo
> String: Usar delimitadores de más de un caracter en split

- src/commons/log.h
- src/commons/string.h
De la nada me encontré con que [este atributo](https://www.keil.com/support/man/docs/armcc/armcc_sam1436458756975.htm) es el que hace que el compilador nos chille cuando la estemos pifiando con `printf(...)`. Al mergear este PR, va a pasar lo mismo en cualquier función de log 🎉 
```c
#include <commons/log.h>
int main() {
t_log* logger = log_create("yo-tengo-tu.log", "I_GOT_YOUR_LOG", 1, 0);
log_info(logger, "%s");
return 0;
}
```
```
$ gcc -g -o main main.c -lcommons
main.c: In function ‘main’:
main.c:5:21: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
5 |     log_info(logger, "%s");
|                    ~^
|                     |
|                     char *
```
> Agregar attributes a funciones printf-like

- src/commons/collections/list.c
- tests/unit-tests/test_list.c
Al parecer si el primer elemento no cumple el filtro la función explota, ya que siempre luego de eliminar el nodo siempre asigna el `previous->next` a la iteración, incluso aunque no exista. Mala mía 😕 
Cambié un toque los tests para que salte el error y lo fixeé.
> Fix: list remove and destroy all by condition

- .dockerignore
- Dockerfile
- src/makefile
Las [nuevas VMs](../../entorno-vms) en Ubuntu 22.04 van a venir con gcc 11.2.0 instalado, por lo que parto de esa versión en el Dockerfile de prueba.
> Build: Actualizo Docker image al nuevo entorno

- src/commons/string.c
- src/commons/string.h
- tests/unit-tests/test_string.c
Este PR incluye:
1. Función `string_replace` (https://github.com/sisoputnfrba/so-commons-library/issues/59). Devuelve:
```C
string_replace("hello", "ello", "ola"); // => "hola"
string_replace("hello", "l", ""); //  => "heo"
string_replace("hello", "o", "o world!"); //  => "hello world!"
string_replace("hello", "not a substring", "yay!"); //  => "hello"
```
Los otros casos los dejé como comportamiento no definido por si lo llegamos a cambiar para que coincida con [`String.prototype.replaceAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll), pero devuelven:
```C
string_replace("hello", "", "x"); //  => "hxexlxlxo"
string_replace("hello", NULL, "x"); //  => "hello"
string_replace(NULL, "a", "x") // => error
``` …
> Strings: replace y n_append

- src/commons/temporal.c
- src/commons/temporal.h
- tests/integration-tests/temporal/main.c
Si por algún motivo misterioso `clock_gettime` tira error, hay un memory leak en `temporal_get_string_time`. También incluí el mensajito que sin querer borré en #123 y acomodé un poco el código para que el formato sea igual al resto.
> temporal_get_string_time: fix memory leak on error

- commons.code-workspace
- src/.vscode/c_cpp_properties.json
- tests/integration-tests/logger/.vscode/c_cpp_properties.json
- tests/integration-tests/logger/.vscode/launch.json
- tests/integration-tests/logger/.vscode/tasks.json
- tests/integration-tests/temporal/.vscode/c_cpp_properties.json
- tests/integration-tests/temporal/.vscode/launch.json
- tests/integration-tests/temporal/.vscode/tasks.json
- tests/unit-tests/.vscode/c_cpp_properties.json
- tests/unit-tests/.vscode/launch.json
- tests/unit-tests/.vscode/tasks.json
- tests/unit-tests/test_string.c
Extracted from https://github.com/sisoputnfrba/foro/issues/3314#issuecomment-1854024419
> Add Code workspace configuration + missing test case

- src/commons/collections/list.c
- src/commons/collections/list.h
- tests/unit-tests/test_list.c
Bueno resulta que hace unos meses arranqué por implementar un `list_iterator_replace()` y terminé reescribiendo toda la implementación de listas usando el iterador 😅 
La verdad que no me había gustado cómo había quedado la implementación actual: la lógica para recorrerla está en cada función por lo que es complicada de leer y explicar (y aparte tiene nested functions, lo cual en Alpine Linux [trae problemas](https://github.com/sisoputnfrba/entorno-vms/pull/12)). Ahora si quisiera mostrarle a un alumno "mirá, así funciona" _creo_ que es más sencillo:
```c
void *list_replace(t_list *self, int index, void *data) {
t_list_iterator self_iterator = list_iterator_init(self);
list_iterator_advance_to_index(&self_iterator, index);
void *old_data = list_iterator_next(&self_iterator); …
```
> List: Iterator replace

- src/commons/log.c
- tests/integration-tests/logger/main.c
relates to #192
- Los integration tests estaban fallando porque no tenían la extensión `.log` al final.
- Agrego un `free()`
> fix: Logger memory leak and integration tests

- .gitignore
- README.md
- commons.code-workspace
- makefile
- src/makefile
- tests/integration-tests/logger/makefile
- tests/integration-tests/temporal/makefile
- tests/unit-tests/makefile
1. Actualizo el makefile de los unit tests para que usen una versión local de CSpec en lugar de chequear que el paquete esté instalado (relates https://github.com/sisoputnfrba/foro/issues/4977)
2. Agrego `-lcrypto` al compilar las commons, así en teoría no haría falta agregarlo luego
3. Hago que el makefile falle temprano si hubo un problema al buildear, en vez de hacer que siga intentando correr los tests
> fix: Download CSpec locally and remove crypto library linkage
